Ygo 66
duelcontrolunit/YGOProAnalyticsServer pull request #59
Opened 2019-06-21 23:31 UTC by szefo09

Cards.AsNoTracking() still create many to many relations,
change from IList to IEnumerable makes Conversion and sorting faster, as it doesn't have to change the objects to List.
Added continue when #main or #side is hit.
Updated test.

2019-06-21 23:32 UTC, szefo09 commented on YGOProAnalyticsServer/EventHandlers/YgoProAnalysisBasedOnDataFromYgoProServer.cs
> -                   && !_duelLogNameAnalyzer.IsDuelVersusAI(duelLog.Name)
Those are unnecessary, as IsAnyBanlist already checks those.

2019-06-22 11:56 UTC, NightAngell requested changes

2019-06-22 11:56 UTC, NightAngell commented on YGOProAnalyticsServer/EventHandlers/YgoProAnalysisBasedOnDataFromYgoProServer.cs
>              return _duelLogNameAnalyzer.IsAnyBanlist(duelLog.Name)
update docs for IsAnyBanlist() (info about internal IsAnyBanlist implementation required if you want remove IsDuelVersusAI and IsNoDeckCheckEnabled checks here)

2019-06-23 19:53 UTC, NightAngell approved these changes

2019-06-23 19:53 UTC, merged