Ygo 84
duelcontrolunit/YGOProAnalyticsServer pull request #86
Opened 2019-11-11 15:02 UTC by szefo09

Add Beta To Official conversion. Please analyze the code fully before accepting the PR to check for any possible issue.

2019-11-12 20:37 UTC, NightAngell approved these changes

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/AdminConfig.cs
> +        public string BetaToOfficialCardApiURL { get; protected set; } = "http://eeriecode.altervista.org/tools/get_beta_cards.php";
Update config.json.template

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/DbModels/Card.cs
> +            ImageUrl.Replace(PassCode.ToString(), newPassCode.ToString());
Why ChangePassCode changes also images urls?

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/Jobs/UpdatesJob.cs
> +                    await betaToOfficialConverter.UpdateCardsFromBetaToOfficial();
Maybe we should update all cards before update beta to official?

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/Services/Converters/BetaCardToOfficialConverter.cs
> +        YgoProAnalyticsDatabase _db;
I believe db access variable should be readonly here.

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/Services/Converters/BetaCardToOfficialConverter.cs
> +        private bool _cardAlreadyExistInOurDatabase(int id)
Empty line before method.

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/Services/Converters/BetaCardToOfficialConverter.cs
> +                    if (_cardAlreadyExistInOurDatabase(officialPassCode))
We don`t need read it from this big list twice.

2019-11-12 20:37 UTC, NightAngell commented on YGOProAnalyticsServer/Services/Converters/BetaCardToOfficialConverter.cs
> +            return betaCardsList;
Empty line before return statement.

2019-11-12 20:37 UTC, NightAngell requested changes
.

2019-11-13 19:17 UTC, szefo09 commented on YGOProAnalyticsServer/DbModels/Card.cs
> +            ImageUrl.Replace(PassCode.ToString(), newPassCode.ToString());
because the image urls are based on card's passcode, so to keep them up-to-date, they are changed with passcode change.

2019-11-13 19:19 UTC, szefo09 commented on YGOProAnalyticsServer/Jobs/UpdatesJob.cs
> +                    await betaToOfficialConverter.UpdateCardsFromBetaToOfficial();
With this order, if a beta card exists, but an official one doesn't, the beta card's passcode will simply update. If both exist, the procedure is longer, as you have to transfer beta's includes into official's. So we want to use the first route if possible.

2019-11-14 09:14 UTC, NightAngell commented on YGOProAnalyticsServer/Services/Converters/BetaCardToOfficialConverter.cs
> +            return card;
Add empty line before return statement.

2019-11-14 10:03 UTC, NightAngell approved these changes

2019-11-14 10:03 UTC, merged